### PR TITLE
Update sigils

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by tmbb** [comment]
It looks great :) Could you please add tests for the new sigils you've added?

**Comment by tmbb** [comment]
This is not directly related to your branch, but just so you know I've tried to split the sigils into their own module to speed up compilation but it turns out it's not trivial because of all the combinators we have to embed *inside* the sigil. Splitting it over modules becomes a major undertaking and not simply a matter of changing the place of some lines.

**Comment by josevalim** [comment]
@tmbb I just pushed the optimization. It does move some of the logic to helper module but if you want I can abstract the logic via a MFArgs. This PR takes the time to compile this file from 13.5s to 4.8s.

**Comment by josevalim** [comment]
I will go ahead and merge this and address feedback later because I want to try this on the new branch. :D

**Pull request merged**
